const menuItems1 = [
  {
    category: "Snacks",
    items: [
      {
        id: 1,
        name: "Samosa",
        price: 3.99,
        description: "Crispy and flaky pastry filled with spiced potatoes.",
        image: "/images/snacks/samosa.jpg",
      },
      {
        id: 2,
        name: "Onion Samosa",
        price: 4.99,
        description: "Mini samosas with spiced onion filling.",
        image: "/images/snacks/onion_samosa.jpg",
      },
      {
        id: 3,
        name: "Egg Bonda",
        price: 6.99,
        description: "Boiled eggs dipped in spiced chickpea batter and fried.",
        image: "/images/snacks/egg_bonda.jpg",
      },
      {
        id: 4,
        name: "Masala Vada",
        price: 6.99,
        description: "Fried lentil fritters made with chana dal and spices.",
        image: "/images/snacks/masala_vada.jpg",
      },
      {
        id: 5,
        name: "Mirchi Bajji",
        price: 6.99,
        description: "Fried green chilies dipped in spiced batter.",
        image: "/images/snacks/mirchi_bajji.jpg",
      },
      {
        id: 6,
        name: "Cut Mirchi",
        price: 6.99,
        description: "Crispy and spicy fried chili slices.",
        image: "/images/snacks/cut_mirchi.jpg",
      },
      {
        id: 7,
        name: "Veg / Onion Pakora",
        price: 6.99,
        description: "Crispy fritters made with onions and gram flour.",
        image: "/images/snacks/onion_pakora.jpg",
      },
      {
        id: 8,
        name: "Punugulu",
        price: 6.99,
        description: "Deep-fried savory fritters made from dosa batter.",
        image: "/images/snacks/punugulu.jpg",
      },
      {
        id: 9,
        name: "Mysore Bonda",
        price: 6.99,
        description: "Soft and fluffy deep-fried dumplings made with urad dal.",
        image: "/images/snacks/mysore_bonda.jpg",
      },
      {
        id: 10,
        name: "Paanipuri",
        price: 6.99,
        description: "Crispy puris filled with spicy and tangy water.",
        image: "/images/snacks/paanipuri.jpg",
      },
      {
        id: 11,
        name: "Samosa Chat",
        price: 6.99,
        description: "Crispy samosas topped with chutneys, curd, and spices.",
        image: "/images/snacks/samosa_chat.jpg",
      },
    ],
  },
  {
    category: "South Indian Tiffins",
    items: [
      {
        id: 12,
        name: "Idly (3)",
        price: 7.99,
        description: "Steamed rice cakes served with sambar and chutney.",
        image: "/images/south_indian_tiffins/idly.jpg",
      },
      {
        id: 13,
        name: "Idly-Ghee / Karam",
        price: 8.99,
        description: "Steamed idly topped with ghee and spicy karam podi.",
        image: "/images/south_indian_tiffins/idly_ghee_karam.jpg",
      },
      {
        id: 14,
        name: "Idly Sambar (2)",
        price: 8.99,
        description: "Idly served with flavorful sambar and coconut chutney.",
        image: "/images/south_indian_tiffins/idly_sambar.jpg",
      },
      {
        id: 15,
        name: "Vada (3)",
        price: 7.99,
        description: "Crispy lentil donuts served with chutneys.",
        image: "/images/south_indian_tiffins/vada.jpg",
      },
      {
        id: 16,
        name: "Vada Sambar (2)",
        price: 8.99,
        description: "Crispy vadas soaked in sambar.",
        image: "/images/south_indian_tiffins/vada_sambar.jpg",
      },
      {
        id: 17,
        name: "Poori (2)",
        price: 8.99,
        description: "Deep-fried flatbread served with potato curry.",
        image: "/images/south_indian_tiffins/poori.jpg",
      },
      {
        id: 18,
        name: "Dosa - Plain",
        price: 7.99,
        description: "Crispy and thin rice crepe served with chutneys.",
        image: "/images/south_indian_tiffins/plain_dosa.jpg",
      },
      {
        id: 19,
        name: "Dosa - Masala/Egg/Onion",
        price: 8.99,
        description: "Stuffed dosa with masala, egg, or onion filling.",
        image: "/images/south_indian_tiffins/masala_dosa.jpg",
      },
      {
        id: 20,
        name: "Dosa - Ghee / Cheese",
        price: 9.99,
        description: "Crispy dosa topped with ghee or cheese.",
        image: "/images/south_indian_tiffins/ghee_dosa.jpg",
      },
      {
        id: 21,
        name: "Pesarattu",
        price: 9.99,
        description: "Green gram dosa served with ginger chutney.",
        image: "/images/south_indian_tiffins/pesarattu.jpg",
      },
      {
        id: 22,
        name: "Uthappam",
        price: 10.99,
        description: "Thick dosa topped with vegetables and spices.",
        image: "/images/south_indian_tiffins/uthappam.jpg",
      },
    ],
  },
  {
    category: "Noodles",
    items: [
      {
        id: 23,
        name: "Veg Noodles",
        price: 10.99,
        description: "Stir-fried noodles with mixed vegetables.",
        image: "/images/noodles/veg_noodles.jpg",
      },
      {
        id: 24,
        name: "Egg Noodles",
        price: 11.99,
        description: "Stir-fried noodles with eggs and vegetables.",
        image: "/images/noodles/egg_noodles.jpg",
      },
      {
        id: 25,
        name: "Chicken Noodles",
        price: 12.99,
        description: "Stir-fried noodles with chicken and vegetables.",
        image: "/images/noodles/chicken_noodles.jpg",
      },
      {
        id: 26,
        name: "Shrimp Noodles",
        price: 14.99,
        description: "Flavorful noodles with shrimp and spices.",
        image: "/images/noodles/shrimp_noodles.jpg",
      },
    ],
  },
  {
    category: "Fried Rice",
    items: [
      {
        id: 27,
        name: "Veg Fried Rice",
        price: 9.99,
        description: "Flavorful fried rice with mixed vegetables.",
        image: "/images/fried_rice/veg_fried_rice.jpg",
      },
      {
        id: 28,
        name: "Egg Fried Rice",
        price: 10.99,
        description: "Fried rice cooked with eggs and vegetables.",
        image: "/images/fried_rice/egg_fried_rice.jpg",
      },
      {
        id: 29,
        name: "Chicken Fried Rice",
        price: 11.99,
        description: "Fried rice with chicken and mixed vegetables.",
        image: "/images/fried_rice/chicken_fried_rice.jpg",
      },
      {
        id: 30,
        name: "Shrimp Fried Rice",
        price: 12.99,
        description: "Fried rice with shrimp and spices.",
        image: "/images/fried_rice/shrimp_fried_rice.jpg",
      },
    ],
  },
  {
    category: "Goat & Lamb Entrees",
    items: [
      {
        id: 31,
        name: "Goat Curry",
        price: 18.99,
        description: "Rich and flavorful goat curry with Indian spices.",
        image: "/images/goat_lamb_entrees/goat_curry.jpg",
      },
      {
        id: 32,
        name: "Gongura Goat",
        price: 18.99,
        description: "Tangy goat curry cooked with gongura leaves.",
        image: "/images/goat_lamb_entrees/gongura_goat.jpg",
      },
      {
        id: 33,
        name: "Lamb Vindaloo",
        price: 19.99,
        description: "Spicy lamb curry cooked in a vinegar-based sauce.",
        image: "/images/goat_lamb_entrees/lamb_vindaloo.jpg",
      },
      {
        id: 34,
        name: "Lamb Palak",
        price: 19.99,
        description: "Tender lamb cooked with creamy spinach gravy.",
        image: "/images/goat_lamb_entrees/lamb_palak.jpg",
      },
      {
        id: 35,
        name: "Lamb Tikka Masala",
        price: 19.99,
        description: "Succulent lamb pieces in a creamy tomato gravy.",
        image: "/images/goat_lamb_entrees/lamb_tikka_masala.jpg",
      },
      {
        id: 36,
        name: "Lamb Rogan Josh",
        price: 19.99,
        description: "Kashmiri-style lamb curry with aromatic spices.",
        image: "/images/goat_lamb_entrees/lamb_rogan_josh.jpg",
      },
      {
        id: 37,
        name: "Lamb Kurma",
        price: 19.99,
        description: "Lamb cooked in a mildly spiced creamy gravy.",
        image: "/images/goat_lamb_entrees/lamb_kurma.jpg",
      },
    ],
  },
  {
    category: "Fish",
    items: [
      {
        id: 38,
        name: "Fish Masala",
        price: 18.99,
        description: "Delicious fish curry cooked in a spiced masala sauce.",
        image: "/images/fish/fish_masala.jpg",
      },
      {
        id: 39,
        name: "Fish Curry",
        price: 18.99,
        description: "Classic fish curry made with coconut and spices.",
        image: "/images/fish/fish_curry.jpg",
      },
    ],
  },
  {
    category: "Veg Appetizer",
    items: [
      {
        id: 40,
        name: "Gobi Manchurian",
        price: 12.99,
        description: "Crispy cauliflower tossed in a tangy Indo-Chinese sauce.",
        image: "/images/veg_appetizer/gobi_manchurian.jpg",
      },
      {
        id: 41,
        name: "Chilli Mushroom",
        price: 12.99,
        description: "Mushrooms stir-fried with chilies and spices.",
        image: "/images/veg_appetizer/chilli_mushroom.jpg",
      },
      {
        id: 42,
        name: "Pepper Mushroom",
        price: 12.99,
        description: "Mushrooms cooked with black pepper and spices.",
        image: "/images/veg_appetizer/pepper_mushroom.jpg",
      },
      {
        id: 43,
        name: "Veg Manchurian",
        price: 12.99,
        description: "Fried vegetable balls in a tangy Manchurian sauce.",
        image: "/images/veg_appetizer/veg_manchurian.jpg",
      },
      {
        id: 44,
        name: "Paneer 65",
        price: 12.99,
        description: "Crispy fried paneer cubes coated in flavorful spices.",
        image: "/images/veg_appetizer/paneer_65.jpg",
      },
      {
        id: 45,
        name: "Chilli Babycorn",
        price: 12.99,
        description: "Babycorn stir-fried with chilies and sauces.",
        image: "/images/veg_appetizer/chilli_babycorn.jpg",
      },
      {
        id: 46,
        name: "Peanut Masala",
        price: 6.99,
        description: "Tangy peanuts mixed with onions, chilies, and spices.",
        image: "/images/veg_appetizer/peanut_masala.jpg",
      },
      {
        id: 47,
        name: "Egg Masala",
        price: 8.99,
        description: "Spiced boiled eggs cooked in a masala sauce.",
        image: "/images/veg_appetizer/egg_masala.jpg",
      },
    ],
  },
  {
    category: "Non-Veg Appetizer",
    items: [
      {
        id: 48,
        name: "Chicken 65",
        price: 14.29,
        description: "Crispy and spicy fried chicken pieces.",
        image: "/images/non_veg_appetizer/chicken_65.jpg",
      },
      {
        id: 49,
        name: "Chilli Chicken",
        price: 14.29,
        description: "Fried chicken tossed in a tangy chili sauce.",
        image: "/images/non_veg_appetizer/chilli_chicken.jpg",
      },
      {
        id: 50,
        name: "Pepper Chicken",
        price: 14.29,
        description: "Chicken stir-fried with black pepper and spices.",
        image: "/images/non_veg_appetizer/pepper_chicken.jpg",
      },
      {
        id: 51,
        name: "Kothimeera Chicken",
        price: 14.29,
        description: "Chicken cooked with fresh coriander and spices.",
        image: "/images/non_veg_appetizer/kothimeera_chicken.jpg",
      },
      {
        id: 52,
        name: "Curryleaves Chicken",
        price: 14.29,
        description: "Chicken stir-fried with curry leaves and spices.",
        image: "/images/non_veg_appetizer/curryleaves_chicken.jpg",
      },
      {
        id: 53,
        name: "Chicken 555",
        price: 14.29,
        description: "Crispy chicken tossed with a special blend of spices.",
        image: "/images/non_veg_appetizer/chicken_555.jpg",
      },
      {
        id: 54,
        name: "Kodi Vepudu",
        price: 14.29,
        description: "Spicy Andhra-style stir-fried chicken.",
        image: "/images/non_veg_appetizer/kodi_vepudu.jpg",
      },
      {
        id: 55,
        name: "Guntur Chicken",
        price: 14.29,
        description: "Fiery chicken curry from the Guntur region.",
        image: "/images/non_veg_appetizer/guntur_chicken.jpg",
      },
      {
        id: 56,
        name: "Chilli Shrimp",
        price: 15.99,
        description: "Spicy shrimp stir-fried with chilies and sauces.",
        image: "/images/non_veg_appetizer/chilli_shrimp.jpg",
      },
      {
        id: 57,
        name: "Apollo Fish",
        price: 15.99,
        description: "Crispy fish fillets tossed in Apollo-style spices.",
        image: "/images/non_veg_appetizer/apollo_fish.jpg",
      },
      {
        id: 58,
        name: "Fish 65",
        price: 15.99,
        description: "Spicy deep-fried fish pieces.",
        image: "/images/non_veg_appetizer/fish_65.jpg",
      },
      {
        id: 59,
        name: "Goat Chukka",
        price: 18.99,
        description: "Dry stir-fried goat with rich spices.",
        image: "/images/non_veg_appetizer/goat_chukka.jpg",
      },
    ],
  },
  {
    category: "Indian Bread",
    items: [
      {
        id: 78,
        name: "Plain Naan",
        price: 2.29,
        description: "Soft and fluffy Indian flatbread.",
        image: "/images/indian_bread/plain_naan.jpg",
      },
      {
        id: 79,
        name: "Butter Naan",
        price: 2.59,
        description: "Naan brushed with melted butter.",
        image: "/images/indian_bread/butter_naan.jpg",
      },
      {
        id: 80,
        name: "Garlic Naan",
        price: 3.29,
        description: "Naan topped with minced garlic.",
        image: "/images/indian_bread/garlic_naan.jpg",
      },
      {
        id: 81,
        name: "Chapathi (2)",
        price: 3.99,
        description: "Soft Indian whole wheat flatbread.",
        image: "/images/indian_bread/chapathi.jpg",
      },
    ],
  },
];

export default menuItems1;
